version: '3.1'

services:
  pedrojs:
    container_name: devenv_ether_goblin
    image: ether-goblin:latest
    restart: always
    volumes:
      - ../conf:/opt/app/conf
    ports:
      - "56550:56550"
