version: '3.1'

services:
  ether-goblin:
    container_name: devenv_ether_goblin
    image: ether-goblin:latest
    restart: always
    volumes:
      - ../conf:/opt/app/conf
      - ../database:/opt/app/database
      - ../keystore:/opt/app/keystore
    ports:
      - "56550:56550"
